package com.example.digitalrefrige.model.dataHolder;


import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.Calendar;
import java.util.Date;

/**
 * Entity class for local database, id is PK and autogenerated by Room
 */
@Entity(tableName = "item_table")
public class Item {
    private String name;
    private String description;
    private Date createDate;
    private String photoPath;


    @PrimaryKey(autoGenerate = true)
    private int id;

    public Item(String name, String description, Date createDate, String photoPath) {
        this.name = name;
        this.description = description;
        this.createDate = createDate;
        this.photoPath = photoPath;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getPhotoPath() {
        return photoPath;
    }

    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }
}
