package com.example.digitalrefrige.model.dataHolder;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.Objects;

/**
 * Entity class for local database, id is PK and autogenerated by Room
 */
@Entity(tableName = "label_table")
public class Label {
    public static Label NONE_LABEL = new Label("UNDEFINED");

    @PrimaryKey(autoGenerate = true)
    private long labelId;

    private String title;

    public Label(String title) {
        this.title = title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public long getLabelId() {
        return labelId;
    }

    public void setLabelId(long labelId) {
        this.labelId = labelId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Label label = (Label) o;
        return labelId == label.labelId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(labelId);
    }

    @Override
    public String toString() {
        return "Label{" +
                "labelId=" + labelId +
                ", title='" + title + '\'' +
                '}';
    }

}
