package com.example.digitalrefrige.model.dataHolder;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity class for local database, id is PK and autogenerated by Room
 */
@Entity(tableName = "label_table")
public class Label {
    @PrimaryKey(autoGenerate = true)
    private int id;

    private String title;

    public Label(String title){
        this.title = title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle(){
        return this.title;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
